[package]
name = "armyknife"
version = "0.1.0"
edition = "2024"
authors = ["Hayato Kawai <fohte@users.noreply.github.com>"]
description = "A multi-purpose CLI tool"
repository = "https://github.com/fohte/armyknife"
license = "MIT"

[dependencies]
