[package]
name = "armyknife"
version = "0.1.2"
edition = "2024"
authors = ["Hayato Kawai <fohte.hk@gmail.com>"]
description = "Personal CLI toolkit written in Rust"
repository = "https://github.com/fohte/armyknife"
license = "MIT"

[[bin]]
name = "a"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.5.53", features = ["derive"] }
dirs = "=6.0.0"
indoc = "2"
regex = "1"
self_update = { version = "=0.42.0", features = ["rustls"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10"
tempfile = "3"
thiserror = "2"

[dev-dependencies]
rstest = "=0.26.1"
