[package]
name = "armyknife"
version = "0.1.1"
edition = "2024"
authors = ["Hayato Kawai <fohte.hk@gmail.com>"]
description = "Personal CLI toolkit written in Rust"
repository = "https://github.com/fohte/armyknife"
license = "MIT"

[[bin]]
name = "a"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "6"
self_update = { version = "0.27", features = ["rustls"], default-features = false }
semver = "1"
