[package]
name = "armyknife"
version = "0.1.0"
edition = "2024"
authors = ["Hayato Kawai <fohte.hk@gmail.com>"]
description = "Personal CLI toolkit written in Rust"
repository = "https://github.com/fohte/armyknife"
license = "MIT"

[[bin]]
name = "a"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
